
SRC			+= lib/atoi.c
SRC			+= lib/lut.c
SRC			+= lib/crc16.c

SRC-$(LIB_LOG)		+= lib/log.c
SRC-$(LIB_CONFIG)	+= lib/config.c

include lib/fatfs/Makefile
include lib/uip/Makefile
include lib/canopen/Makefile
include lib/battdb/Makefile
include lib/httpd/Makefile

