
SRC-$(APP_BCI_MOD_NMEA2000) += $(wildcard app/bci/modules/nmea2000/*.c)
SRC-$(APP_BCI_MOD_SMA)      += $(wildcard app/bci/modules/sma/*.c)
SRC-$(APP_BCI_MOD_PHILIPPI) += $(wildcard app/bci/modules/philippi/*.c)
