
SRC		+= bios/arch.c
SRC		+= bios/cmd.c
SRC		+= bios/dev.c
SRC		+= bios/evq.c
SRC		+= bios/main.c
SRC		+= bios/printd.c
SRC		+= bios/uart.c
SRC		+= bios/sysinfo.c
SRC		+= bios/logd.c

SRC-$(DRV_ADC)		+= bios/adc.c
SRC-$(DRV_BUTTON)	+= bios/button.c
SRC-$(DRV_CAN)		+= bios/can.c
SRC-$(DRV_FAN)		+= bios/fan.c
SRC-$(DRV_LED)		+= bios/led.c
SRC-$(DRV_EEPROM)	+= bios/eeprom.c
SRC-$(DRV_RELAY)	+= bios/relay.c
SRC-$(DRV_RTC)		+= bios/rtc.c
SRC-$(DRV_SPI)		+= bios/spi.c
SRC-$(DRV_GPIO)		+= bios/gpio.c
SRC-$(DRV_MMC)		+= bios/mmc.c
SRC-$(DRV_I2C)		+= bios/i2c.c

