
include drv/gpio/Makefile
include drv/can/Makefile
include drv/fan/Makefile
include drv/button/Makefile
include drv/led/Makefile
include drv/relay/Makefile
include drv/adc/Makefile
include drv/rtc/Makefile
include drv/uart/Makefile
include drv/eeprom/Makefile
include drv/spi/Makefile
include drv/mmc/Makefile

LINTFLAGS += '+libm(drv\*\*-linux.c)'
LINTFLAGS += '+libm(drv\*\*-stm32.c)'
