
SRC-$(DRV_UART_LINUX)	+= drv/uart/uart-linux.c
SRC-$(DRV_UART_WIN32)	+= drv/uart/uart-win32.c
SRC-$(DRV_UART_STM32)	+= drv/uart/uart-stm32.c
SRC-$(DRV_UART_LPC)	+= drv/uart/uart-lpc.c
SRC-$(DRV_UART_AVR)	+= drv/uart/uart-avr.c
SRC-$(DRV_UART_STDIO)	+= drv/uart/uart-stdio.c

