
SRC-$(DRV_GPIO_DUMMY)	+= drv/gpio/gpio-dummy.c
SRC-$(DRV_GPIO_STM32)	+= drv/gpio/gpio-stm32.c
SRC-$(DRV_GPIO_LPC)	+= drv/gpio/gpio-lpc.c
SRC-$(DRV_GPIO_AVR)	+= drv/gpio/gpio-avr.c
SRC-$(DRV_GPIO_SPI)	+= drv/gpio/gpio-spi.c

