
include plat/linux/Makefile
include plat/bci/Makefile
include plat/bms/Makefile
include plat/bms-avr/Makefile
include plat/voltcraft/Makefile
include plat/lpc-p1343/Makefile
include plat/win32/Makefile

